INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Áo Khoác - NAM', '1', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Áo Vest - NAM', '1', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Áo Nỉ - NAM', '1', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Quần Jeans - NAM', '1', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Quần Âu - NAM', '1', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Quần Short - NAM', '1', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Áo khoác - NỮ', '2', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Áo len - NỮ', '2', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Đồ ngủ - NỮ', '2', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Quần đùi - NỮ', '2', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Quần jeans - NỮ', '2', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Đầm/Váy - NỮ', '2', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Apple - ĐIỆN THOẠI', '3', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Samsung - ĐIỆN THOẠI', '3', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Xiaomi - ĐIỆN THOẠI', '3', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Nokia - ĐIỆN THOẠI', '3', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Dell - LAPTOP ', '4', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('HP - LAPTOP', '4', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Sony - LAPTOP', '4', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Giày - NAM', '5', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Dép - NAM', '5', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Giày - NỮ', '6', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Dép - NỮ', '6', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Loa - ĐIỆN TỬ', '7', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Tive - ĐIỆN TỬ', '7', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Đồng Hồ Nam - ĐỒNG HỒ', '8', '1');
INSERT INTO `shopee_data`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOW`) VALUES ('Đồng Hồ Nữ- ĐỒNG HỒ', '8', '1');
